package com.solvd.atm.enums;

public enum AtmState {
    INITIAL,
    CARD_VALIDATED,
    PIN_VALIDATED,
    CHANGE_PIN,
    MAKE_TRANSFER,
    CHECK_BALANCE,
    VIEW_TRANSACTION_HISTORY,
    VIEW_ALL_TRANSACTION_HISTORY,
    WITHDRAWAL,
    DEPOSIT,
    CHANGE_BLOCKED_CARDS,
    VIEW_ALL_ACCOUNTS,
    VIEW_ALL_CARDS,
    IDLE,
    VIEW_ACCOUNT,
    VIEW_CARD,
    VIEW_ALL_USERS,
    CREATE_USER,
    ADD_CARD_TO_USER
}
